In [8]:
import numpy as np

a = np.array([15, 25, 35]) 
print(type(a)) 
print(a.shape) 
print(a[0], a[1], a[2]) 
a[0] = 5 
print(a) 

b = np.array([[1,2,3],[4,5,6]]) 
print(b.shape) 
print(b[0, 0], b[0, 1], b[1, 0]) 

a = np.zeros((2,2)) 
print(a) 
 
b = np.ones((1,2)) 
print(b) 

c = np.full((2,2), 7) 
print(c)

<class 'numpy.ndarray'>
(3,)
15 25 35
[ 5 25 35]
(2, 3)
1 2 4
[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]


In [6]:
d = np.eye(2) 
print(d) 

e = np.random.random((2,2)) 
print(e) 

np.array(np.mat('2 23; 30 52')) 
np.array(np.mat('5 25; 45 65'), subok=True) 

[[1. 0.]
 [0. 1.]]
[[0.81448666 0.66654231]
 [0.05050932 0.23938284]]


matrix([[ 5, 25],
        [45, 65]])

In [7]:

a = np.arange(10) 
print (a[2:5]) 

a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a[1:]) 

a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print (a[...,1]) 
print (a[1,...]) 
print (a[...,1:])

x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]]
print (y) 

x = np.array([[ 0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9, 10, 11]])
print (x[x > 5]) 

[2 3 4]
[[3 4 5]
 [4 5 6]]
[2 4 5]
[3 4 5]
[[2 3]
 [4 5]
 [5 6]]
[1 4 5]
[ 6  7  8  9 10 11]
