In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
df=pd.read_csv("D:\\linera_regression_multivariate\\task\\hiring.csv")

In [3]:
df

experience  test_score  interview_score  salary
0           0           8                9   50000
1           0           8                6   45000
2           5           6                7   60000
3           2          10               10   65000
4           7           9                6   70000
5           3           7               10   62000
6          10           7                7   72000
7          11           7                8   80000

In [4]:
df.head(3)

experience  test_score  interview_score  salary
0           0           8                9   50000
1           0           8                6   45000
2           5           6                7   60000

In [5]:
reg=linear_model.LinearRegression()

In [6]:
reg.fit(df[['experience','test_score','interview_score']],df.salary)

LinearRegression()

In [7]:
reg.predict([[2,9,6]])

C:\Users\Admin\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [8]:
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [9]:
reg.intercept_

14992.65144669314

In [10]:
2*2922.26901502+9*2221.30909959+6*2147.48256637+14992.65144669314

53713.86677126314

In [11]:
reg.predict([[12,10,10]])

C:\Users\Admin\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])

In [12]:
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [13]:
reg.intercept_

14992.65144669314

In [14]:
12*2922.26901502+10*2221.30909959+10*2147.48256637+14992.65144669314

93747.79628653315