In [1]:
import numpy as np


In [2]:
a=np.array([1,2,3])

In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
print(a.shape)

(3,)


In [5]:
print(a[0],a[1],a[2])

1 2 3


In [6]:
print(a)

[1 2 3]


In [7]:
a[0]=5

In [8]:
print(a)

[5 2 3]


In [9]:
b=np.array([[1,2,3],[4,5,6]])

In [10]:
print(b.shape)

(2, 3)


In [11]:
print(b[0,0],b[0,1],b[1,0])

1 2 4


In [14]:
a=np.zeros((2,2))

In [15]:
print(a)

[[0. 0.]
 [0. 0.]]


In [16]:
b=np.ones((1,2))

In [17]:
print(b)

[[1. 1.]]


In [18]:
c=np.full((2,2),7)

In [19]:
print(c)

[[7 7]
 [7 7]]


In [21]:
d=np.eye(2)

In [22]:
print(d)

[[1. 0.]
 [0. 1.]]


In [23]:
e=np.random.random((2,2))

In [24]:
print(e)

[[0.57263315 0.10791724]
 [0.24653152 0.29271112]]


In [25]:
np.array(np.mat('1 2; 3 4'))

array([[1, 2],
       [3, 4]])

In [26]:
np.array(np.mat('1 2; 3 4'),subok=True)

matrix([[1, 2],
        [3, 4]])

In [28]:
a=np.arange(10)

In [29]:
print(a[2:5])

[2 3 4]


In [30]:
a=np.array([[1,2,3],[3,4,5],[4,5,6]])

In [31]:
print(a[1:])

[[3 4 5]
 [4 5 6]]


In [32]:
print(a[...,1])

[2 4 5]


In [33]:
print(a[1,...])

[3 4 5]


In [34]:
print(a[...,1:])

[[2 3]
 [4 5]
 [5 6]]


In [35]:
x=np.array([[1,2],[3,4],[5,6]])

In [37]:
y=x[[0,1,2],[0,1,0]]

In [38]:
print(y)

[1 4 5]


In [39]:
x=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])

In [40]:
print(x[x>5])

[ 6  7  8  9 10 11]


In [41]:
print(x[x<5])

[0 1 2 3 4]
